### PR TITLE
Fix building datasets list

### PR DESCRIPTION
**Pull request by ericfranz**
Requirements changed so that now datasets are any directory containing a file with extension ".rds" instead of a file with the filename "data.rds".

Besides the fix for the check, two other commits made it easier to debug and switch to a functional approach using glob (in a separate commit to retain the easy option to revert to find if new requirements call for more complex logic).

**Note: I branched off #32 so that should be merged into master first**

### CODE REVIEW

**Comment by ericfranz** [comment]
Reverted glob. Normally glob is really nice, powerful simple.

But it picks up non-datasets in an edge case. That edge case is if a sub directory `bar/` in a dataset `foo/` contains a file ending in `.rds`, the glob will pick up `bar/` as a dataset, but the find approach will not. So `find` is now preferred.

**Comment by ericfranz** [comment]
Oops, should have realized I could have just updated the MappingsHelperTest and ran the tests to guide the change.

**Comment by ericfranz** [comment]
Also updated tests to:

1. use temporary dirs under APP/tmp instead of /tmp since /tmp doesn't handle NFS4 acls and data APP/data directory is not versioned
2. comment out failing test that might not be relevant if switching to cron task to fix permissions

**Comment by ericfranz** [comment]
And I forgot about `ApplicationController.helpers` so there is that.

**Review by MorganRodgers — APPROVED** [review]
This all looks good. For some reason the test began failing during model validation. When it's used in the application validation is called manually, but not during construction. I discovered that removing two redundant `prescence` checks for app and dataset the test started passing.

**Comment by MorganRodgers** [comment]
@ericfranz take a look at the last commit where I fixed the test failing. If you're good with my addition then I declare this ready to merge.

**Comment by ericfranz** [comment]
Yes except that you can use `id -gn` instead of `groups | cut -d ' ' -f 1`. I'll update and merge.

```
efranz@owens-login04:~$ diff <(id -gn) <(echo "$(groups | cut -d ' ' -f 1)")
efranz@owens-login04:~$
```

**Pull request merged**
